# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='fiot',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntest.proto\x12\x04\x66iot\"l\n\x05Param\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\x12\x1e\n\x04\x63ond\x18\x04 \x01(\x0e\x32\x10.fiot.Param.Cond\"\"\n\x04\x43ond\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03MIN\x10\x01\x12\x07\n\x03MAX\x10\x02\"^\n\x03Res\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x1b\n\x04tags\x18\x02 \x03(\x0e\x32\r.fiot.Res.Tag\"+\n\x03Tag\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x32\xa7\x01\n\x04\x46IOT\x12\"\n\x06Simple\x12\x0b.fiot.Param\x1a\t.fiot.Res\"\x00\x12(\n\nStreamResp\x12\x0b.fiot.Param\x1a\t.fiot.Res\"\x00\x30\x01\x12\'\n\tStreamReq\x12\x0b.fiot.Param\x1a\t.fiot.Res\"\x00(\x01\x12(\n\x08\x42iStream\x12\x0b.fiot.Param\x1a\t.fiot.Res\"\x00(\x01\x30\x01\x62\x06proto3'
)



_PARAM_COND = _descriptor.EnumDescriptor(
  name='Cond',
  full_name='fiot.Param.Cond',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MIN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MAX', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=94,
  serialized_end=128,
)
_sym_db.RegisterEnumDescriptor(_PARAM_COND)

_RES_TAG = _descriptor.EnumDescriptor(
  name='Tag',
  full_name='fiot.Res.Tag',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=181,
  serialized_end=224,
)
_sym_db.RegisterEnumDescriptor(_RES_TAG)


_PARAM = _descriptor.Descriptor(
  name='Param',
  full_name='fiot.Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='fiot.Param.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='fiot.Param.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='fiot.Param.z', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cond', full_name='fiot.Param.cond', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PARAM_COND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=128,
)


_RES = _descriptor.Descriptor(
  name='Res',
  full_name='fiot.Res',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='fiot.Res.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tags', full_name='fiot.Res.tags', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RES_TAG,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=224,
)

_PARAM.fields_by_name['cond'].enum_type = _PARAM_COND
_PARAM_COND.containing_type = _PARAM
_RES.fields_by_name['tags'].enum_type = _RES_TAG
_RES_TAG.containing_type = _RES
DESCRIPTOR.message_types_by_name['Param'] = _PARAM
DESCRIPTOR.message_types_by_name['Res'] = _RES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Param = _reflection.GeneratedProtocolMessageType('Param', (_message.Message,), {
  'DESCRIPTOR' : _PARAM,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:fiot.Param)
  })
_sym_db.RegisterMessage(Param)

Res = _reflection.GeneratedProtocolMessageType('Res', (_message.Message,), {
  'DESCRIPTOR' : _RES,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:fiot.Res)
  })
_sym_db.RegisterMessage(Res)



_FIOT = _descriptor.ServiceDescriptor(
  name='FIOT',
  full_name='fiot.FIOT',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=227,
  serialized_end=394,
  methods=[
  _descriptor.MethodDescriptor(
    name='Simple',
    full_name='fiot.FIOT.Simple',
    index=0,
    containing_service=None,
    input_type=_PARAM,
    output_type=_RES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamResp',
    full_name='fiot.FIOT.StreamResp',
    index=1,
    containing_service=None,
    input_type=_PARAM,
    output_type=_RES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamReq',
    full_name='fiot.FIOT.StreamReq',
    index=2,
    containing_service=None,
    input_type=_PARAM,
    output_type=_RES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BiStream',
    full_name='fiot.FIOT.BiStream',
    index=3,
    containing_service=None,
    input_type=_PARAM,
    output_type=_RES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FIOT)

DESCRIPTOR.services_by_name['FIOT'] = _FIOT

# @@protoc_insertion_point(module_scope)
